### PR TITLE
Python3, PEP8 and Title -> Filename

### PR DESCRIPTION
**Pull request by onlurking**
- Ported the code to Python 3.
- Made PEP 8 compliant.
- Saves the presentations by title now (through regex parsing).
- Strips special characters in title.

### CODE REVIEW

**Comment by ryukinix** [comment]
[uesli-mode]
ACCEPT THIS SHIT NOW, YOUR MOTHER FUCKER! THIS FUCKING PR ALREADY TAKES ONE YEAR WAITING YOUR FUCKING FUCKER ACCEPTATION.

**Comment by erinus** [comment]
Sorry. I dont get this notification. Please watch your mouth. YOU MOTHER FUCKER.

**Comment by ryukinix** [comment]
Thanks. :heart: 
why-for-the-glory-of-satan-of-course

**Comment by onlurking** [comment]
wut

**Comment by chrisfls** [comment]
@ryukinix I'll laugh about this for years. Thanks XD

**Comment by ryukinix** [comment]
Câncer pression

**Comment by rafaelcn** [comment]
Ah, the mighty @ryukinix hahahahah!

**Comment by erinus** [comment]
If you didn't get pr notification and you got 'mother fucker' comment from someone, you can keep polite. Okey. You are saint.

**Comment by erinus** [comment]
You can say any curse words to show your angry, and I can take it. But don't relate my family.

**Comment by chrisfls** [comment]
@erinus is a saint, but I don't think @ryukinix meant to insult your family

http://www.urbandictionary.com/define.php?term=mother%20fucker

**Comment by erinus** [comment]
I ain't saint, but I won't do this like you. Pity you. 
https://en.m.wikipedia.org/wiki/Motherfucker

**Comment by chrisfls** [comment]
😆

**Comment by ryukinix** [comment]
Sorry. I was "Absolutely Putaço". Of course your mother doesn't has any relation with that. It's just yourself. Sorry. And, again, thanks for add the WONDERFUL pull-request. 
absolutely-putaco

**Pull request merged**
